# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_username', models.CharField(max_length=50)),
                ('manager_name', models.CharField(max_length=250)),
            ],
        ),
    ]
