# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('pro_price', models.CharField(max_length=250)),
                ('pro_qty', models.CharField(max_length=250)),
            ],
        ),
    ]
