# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0007_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=250)),
            ],
        ),
    ]
